### ISSUE TITLE
Help me to solve this issues plz

### ISSUE THREAD

**Issue by yb536** [strin/BayesPA#2]
when I enter
$sudo python setup.py install
I got this follow blew:

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/medlda
copying medlda/__init__.py -> build/lib.linux-x86_64-2.7/medlda
running build_ext
building 'libbayespagibbs' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/medlda
creating build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA
creating build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src
creating build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/ap.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/ap.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/cholesky.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/cholesky.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/cokus.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/cokus.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/InverseGaussian.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/InverseGaussian.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/Mapper.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/Mapper.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/MVGaussian.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/MVGaussian.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/objcokus.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/objcokus.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/spdinverse.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/spdinverse.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/Document.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/Document.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/utils/Sample.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/Sample.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/OnlineGibbsMedLDA.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/OnlineGibbsMedLDA.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=0 -DMINOR_VERSION=1 -Imedlda/OnlineGibbsMedLDA/inc -Imedlda/OnlineGibbsMedLDA/inc/utils -I/usr/include/python2.7 -c medlda/OnlineGibbsMedLDA/src/OnlineGibbsMedLDAWrapper.cpp -o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/OnlineGibbsMedLDAWrapper.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/ap.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/cholesky.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/cokus.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/InverseGaussian.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/Mapper.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/MVGaussian.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/objcokus.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/spdinverse.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/Document.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/utils/Sample.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/OnlineGibbsMedLDA.o build/temp.linux-x86_64-2.7/medlda/OnlineGibbsMedLDA/src/OnlineGibbsMedLDAWrapper.o -L/opt/local/lib/ -lboost_python-mt -o build/lib.linux-x86_64-2.7/libbayespagibbs.so
/usr/bin/ld: cannot find -lboost_python-mt
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

libboost-all-dev is already the newest version.
gcc-4.8 is already the newest version.
python-numpy is already the newest version.
Plz help.

**Comment by strin** [comment]
It seems that you are using linux. I realized in OS X installation file, we have a command line for installing Boost.Python:

brew install boost-python --cc=gcc-4.9

In Ubuntu, could you please try the following equivalent command?

sudo apt-get install libboost-python-dev

**Comment by strin** [comment]
The problem is solved by creating the following symbolic link:

sudo ln -s /usr/lib/libboost_python-mt-py27.so /usr/lib/libboost_python-mt.so
